### ISSUE TITLE
Not able to download package

### ISSUE THREAD

**Issue by nettum** [nfourtythree/craft3-vcard#1]
Hi!

I see that this package is in the plugin-store, but I'm not able to install it neither in the admin CP (will give 504 Gateway Time-out) or using composer.  
`composer require nfourtythree/craft3-vcard` in a newly created folder just to test gives me the following error:
```
  [InvalidArgumentException]                                                                                                                                                                                       
  Could not find a matching version of package nfourtythree/craft3-vcard. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).
```

I'm able to download the package if I add
```
  "repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/nfourtythree/craft3-vcard.git"
    }
  ],
```
to `package.json` and run `composer require nfourtythree/vcard` (note that the name in composer.json is not prefixed with craft3).

Is it not added to packagist? Concider doing so and/or standardize the name of the plugin if  you want others to be able to use it directly from the store :smile:

**Comment by nfourtythree** [comment]
Hi @nettum 

Sorry, this reply is way overdue I have added this to [packagist](https://packagist.org/packages/nfourtythree/vcard), I did it shortly after you raised this issue.

Thanks for pointing it out, was an oversight on my part!
