### ISSUE TITLE
ROLE is missing

### ISSUE THREAD

**Issue by stefanfriedrich** [nfourtythree/craft3-vcard#20]
The field for "ROLE" seems to be missing, compared with the VCard PHP library.
$vcard->addRole('Data Protection Officer');

Any plans to add this in the (near) future? This would be great.

**Comment by nfourtythree** [comment]
Hi @stefanfriedrich 

Thank you for bringing this up.

The following versions have been released with this addition included:

- version `3.1.0` for Craft 5
- version `2.1.0` for Craft 4

Thanks!
