### ISSUE TITLE
Instructions for salt are too vague.

### ISSUE THREAD

**Issue by jpwdesigns** [nfourtythree/craft3-vcard#21]
I'm working on getting this installed but as the instructions are too vague, I am having to trouble shoot this. Please show an example in your documentation. Thanks for a cool plugin!

**Comment by jpwdesigns** [comment]
This should do it:
`
return [
   'salt' => null,
];
`
Found searching the codebase for "salt"

**Comment by nfourtythree** [comment]
Hi @jpwdesigns 

Sorry the instructions seem a little vague will get those updated.

One thing to note is please make sure you have a value in your `salt` config property. This is for security reasons.

Thanks
