### ISSUE TITLE
Craft 5 Support

### ISSUE THREAD

**Issue by joelzerner** [nfourtythree/craft3-vcard#22]
Just checking to see if this plugin will be ported to Craft 5 and if so, what the timing is?

**Comment by alexanderloewe** [comment]
That would interest me too

**Comment by alexanderbuergin** [comment]
Any update?

**Comment by nfourtythree** [comment]
Hi all

My sincere apologies for the radio silence on this one.

I will look at it this week to get a compatible version out.

Again, sorry for the delay!

Thanks!

**Comment by alexanderbuergin** [comment]
@ Nathaniel Thanks

**Comment by nfourtythree** [comment]
Hi All

I have just pushed version `3.0` which provides Craft 5 compatibility.

To get this version, change your `nfourtythree/vcard` requirement in your project's `composer.json` to:

```json
"require": {
  "nfourtythree/vcard": "^3.0.0",
  "...": "..."
}
```

Then run `composer update`.

Thanks!
