### ISSUE TITLE
vcard not downloading correctly on mobile

### ISSUE THREAD

**Issue by davefischoff** [nfourtythree/craft3-vcard#3]
I'm using the craft3-vcard plugin on a new site I'm building and it's working great on desktop, but vcards aren't downloading correctly on mobile devices. On iOS, I get a prompt asking if I want to download a .html version of the file, and downloading it just adds the file to iCloud Drive instead of opening the vcard with the option to save to Contacts. Here's a screenshot of the issue:

<img width="349" alt="Screen Shot 2020-04-23 at 12 18 25 PM" src="https://user-images.githubusercontent.com/7649934/80123631-27898c80-855d-11ea-948d-291bb57e38db.png">

On Android, the vcard download simply fails:

<img width="886" alt="Screen Shot 2020-04-23 at 12 27 38 PM" src="https://user-images.githubusercontent.com/7649934/80124223-f067ab00-855d-11ea-99d6-3c16bd5d1160.png">

The site is running Craft 3.3.18.1. I've tested downloading vcards from another site on these devices and they download correctly, so I don't think it's a device settings issue.

**Comment by nfourtythree** [comment]
Hi @davefischoff 

I have just tried to replicate this with the example code in the readme and the latest install of Craft and everything seems to work as expected (Note: this is on iOS 14).

[Video](https://x.n43.me/KouweJZp)

A thing to try would be removing some of the data in the vcard to see if there is anything that might be throwing it off.

Thanks.

**Comment by nfourtythree** [comment]
Thank you for pointing this out and apologies for the delay in actioning this item.

A release with this fix in it will be out shortly. Just to note, in an effort to keep up to date with everything the Craft requirement has been bumped to the latest version of the CMS.

Thanks!
