### ISSUE TITLE
Header issue

### ISSUE THREAD

**Issue by mediagirl** [nfourtythree/craft3-vcard#6]
I had no luck getting the download working until I incorporated this fix posted as a Pull Request into the code.

Can you incorporate this pull request into the addon to get things working correctly with the header?
https://github.com/nfourtythree/craft3-vcard/pull/5

**Comment by nfourtythree** [comment]
Thank you for pointing this out and apologies for the delay in actioning this item.

A release with this fix in it will be out shortly. Just to note, in an effort to keep up to date with everything the Craft requirement has been bumped to the latest version of the CMS.

Thanks!
