### ISSUE TITLE
Fax number and State

### ISSUE THREAD

**Issue by michalbulla** [nfourtythree/craft3-vcard#7]
Hi there, 

I'm not able to set 
1. The Fax number - I tried to set the type to "FAX", but it saved it as a phone number, not fax.
2. US State in the address field. I tried to use the region, but It didn't work. 

Could you please help me with this?

Thank you

**Comment by nfourtythree** [comment]
Hi @michalbulla 

Thank you for pointing this out, it appears to be an issue with the underlying library. For the moment I have pushed a fix that should solve this issue.

Apologies for the delay in actioning this issue.

A release that includes this fix will be out shortly.

Thanks!

**Comment by michalbulla** [comment]
> Hi @michalbulla
> 
> Thank you for pointing this out, it appears to be an issue with the underlying library. For the moment I have pushed a fix that should solve this issue.
> 
> Apologies for the delay in actioning this issue.
> 
> A release that includes this fix will be out shortly.
> 
> Thanks!

Hi there, 

We used different approach already, but still thanks for the fix ... at least, it will work for other users.
