### ISSUE TITLE
Download Problem vcf

### ISSUE THREAD

**Issue by alexanderbuergin** [nfourtythree/craft3-vcard#9]
On Android and iPhone we have the problem that the vCard is opened as html live so that the vcf is shown is stead of the vCard

I think the header is not set to something like this:
{% header "Content-Type: text/x-vcard; charset=utf-8" %} 

This is my Code:
```
	{% set vcardTeam = siteUrl ~ craft.imager.transformImage(entry.portraitImage.one, { width: 250, height: 250, format: 'jpg' }) %}
	{% set vcardAddress = gloAddress.addressStreet ~ ' ' ~ gloAddress.addressNr %}
	{% set options = {
		photo: vcardTeam,
		firstName: entry.firstname,
		lastName: entry.lastname,
		prefix: entry.salutation,
		company: gloAddress.company,
		jobTitle: entry.jobFunction,
		url: gloAddress.website,
		email: [{ address: entry.eMail, type: "WORK" }, entry.eMail ],
		phoneNumber: [ entry.phone, { number: entry.phone }],
		address: [{
			name: gloAddress.company,
			street: vcardAddress,
			city: gloAddress.addressCity,
			zip: gloAddress.addressZip,
			country: 'Schweiz',
			type: "WORK;PARCEL;POSTAL"
		}],
	} %}
```

**Comment by nfourtythree** [comment]
Thank you for pointing this out and apologies for the delay in actioning this item.

A release with this fix in it will be out shortly. Just to note, in an effort to keep up to date with everything the Craft requirement has been bumped to the latest version of the CMS.

Thanks!
